# Travis-CI Build for charybdis
# see travis-ci.org for details

language: cpp

git:
  submodules: false

#notifications:
#  webhooks:
#    urls:
#    - http://zemos.net:6699/
#    on_success: always
#    on_failure: always
#    on_start: always

#matrix:
#  include:
#  - os: linux
#    dist: xenial
#    sudo: required
#    compiler: g++-6
#    addons:
#      apt:
#        packages:
#        - ['gcc-6', 'g++-6']
#        - ['libssl-dev', 'libsodium-dev']
#        - ['automake', 'autoconf', 'autoconf2.13', 'autoconf-archive', 'libtool', 'shtool']
#    env:
#    - CCOMPILER=gcc-6
#    - CXXCOMPILER=g++-6
#    - WITH_INCLUDED_BOOST=--with-included-boost
#    - WITH_INCLUDED_ROCKSDB=--with-included-rocksdb=shared
#    - WITH_INCLUDED_JS=
#    # - WITH_INCLUDED_JS=--with-included-js=shared

#  - os: linux
#    dist: xenial
#    group: unstable
#    sudo: required
#    compiler: clang-3.9
#    addons:
#      apt:
#        sources:
#        - ubuntu-toolchain-r-test
#        - llvm-toolchain-trusty-3.9
#        packages:
#        - clang-3.9
#        - gcc-6
#        - g++-6
#        - ['automake', 'autoconf', 'autoconf2.13', 'autoconf-archive', 'libtool', 'shtool']
#    env:
#    - CCOMPILER=clang-3.9
#    - CXXCOMPILER=clang++-3.9
#    - WITH_INCLUDED_BOOST=--with-included-boost
#    - WITH_INCLUDED_ROCKSDB=--with-included-rocksdb=shared
#    - WITH_INCLUDED_JS=--with-included-js=shared

#  - os: osx
#    compiler: clang
#    env:
#    - CCOMPILER=clang
#    - CXXCOMPILER=clang++
#    - LIBTOOLIZE=glibtoolize
#    - WITH_INCLUDED_BOOST=--with-included-boost
#    - WITH_INCLUDED_ROCKSDB=--with-included-rocksdb=shared
#    # - WITH_INCLUDED_JS=--with-included-js=shared
#
#osx_image: xcode7.3

script:
- export CC=$CCOMPILER CXX=$CXXCOMPILER
- git rev-parse --verify HEAD
- m4 --version
- autoconf --version
- automake --version
- make --version
- $CC --version
- $CXX --version
- time bash autogen.sh
- time ./configure $WITH_INCLUDED_BOOST $WITH_INCLUDED_ROCKSDB $WITH_INCLUDED_JS CC=$CC CXX=$CXX
- time make -j4
- time make -j4 install
